# Generated by Django 5.0.6 on 2024-05-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='client',
        ),
    ]
