# Generated by Django 4.2.13 on 2024-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_log_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Ошибка', 'Ошибка'), ('Успешно завершена', 'Успешно завершена')], default='created', max_length=20, verbose_name='статус попытки рассылки'),
        ),
    ]
